name: Deploy to EC2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: EC2 SSH 접속하여 전체 배포 실행
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          command_timeout: 666s
          script: |
            cd ~/fair_back
            git pull origin main

            echo "JAR 빌드 시작"
            ./mvnw clean package -DskipTests

            echo "기존 컨테이너 종료 및 정리"
            docker-compose down || true

            echo "Docker 이미지 빌드 및 컨테이너 실행"
            docker-compose up -d --build
